server:
  port: 8082

spring:
  application:
    name: doctor-service
  
  datasource:
    url: jdbc:postgresql://localhost:5433/doctor_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  
  # Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 minutes in milliseconds
      cache-null-values: false

logging:
  level:
    com.hospital.doctor: DEBUG
    org.hibernate.SQL: DEBUG
