server:
  port: 8083

spring:
  application:
    name: appointment-service
  
  datasource:
    url: jdbc:postgresql://localhost:5434/appointment_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# External service URLs
services:
  patient:
    url: http://localhost:8081/api/v1/patients
  doctor:
    url: http://localhost:8082/api/v1/doctors

logging:
  level:
    com.hospital.appointment: DEBUG
    org.hibernate.SQL: DEBUG
