spring:
  application:
    name: billing-service
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/billing_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8084

# Service URLs for inter-service communication
services:
  patient:
    url: ${SERVICES_PATIENT_URL:http://localhost:8081/api/v1/patients}
  appointment:
    url: ${SERVICES_APPOINTMENT_URL:http://localhost:8083/api/v1/appointments}

logging:
  level:
    com.hospital.billing: DEBUG
    org.springframework.web: INFO
